### ISSUE TITLE
Pico_1140 and the newest no-OS-ff15 Rev 10.02.2023

### ISSUE THREAD

**Issue by guidol70** [Isysxp/Pico_1140#7]
Dear Ian,
while try to compile Pico_1140 with the newest pico-dsk v1.50 
and no-OS-ff15 Rev **10.02.2023** I do get the following error:
(PS: I did use your "old" **stdio_usb_descriptors.c**)

```
[ 21%] Building C object CMakeFiles/Pico_1140.dir/hw_config.c.obj
/home/pi/pico/Pico_1140/Pico_1140_DC/hw_config.c: In function 'spi_dma_isr':
/home/pi/pico/Pico_1140/Pico_1140_DC/hw_config.c:73:22: warning: implicit declaration of function 'spi_irq_handler' [-Wimplicit-function-declaration]
   73 | void spi_dma_isr() { spi_irq_handler(&spis[0]); }

```

```
[ 92%] Linking CXX executable Pico_1140.elf
/usr/lib/gcc/arm-none-eabi/12.2.1/../../../arm-none-eabi/bin/ld: CMakeFiles/Pico_1140.dir/hw_config.c.obj: in function `spi_dma_isr':
hw_config.c:(.text.spi_dma_isr+0x4): undefined reference to `spi_irq_handler'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Pico_1140.dir/build.make:1655: Pico_1140.elf] Error 1
make[1]: *** [CMakeFiles/Makefile2:1509: CMakeFiles/Pico_1140.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```

The error is from the no-OS-ff15 Rev 10.02.2023 and **NOT from the new pico-dsk v1.50**
With a older version of no-OS-ff15 or no-OS-ff14a it does compile fine.

![Pico_1140_pico-sdk_v1_50](https://user-images.githubusercontent.com/5121124/218313929-ad13a2d8-8a69-4902-9e26-335c19eb6a16.jpg)

New new one is smaller than your file and has less entrys:
[stdio_usb_descriptors_v150.zip](https://github.com/Isysxp/Pico_1140/files/10716044/stdio_usb_descriptors_v150.zip)

[older_no-OS-ff15.zip](https://github.com/Isysxp/Pico_1140/files/10716142/older_no-OS-ff15.zip)

Kind regards
Guido

**Comment by guidol70** [comment]
Dear Ian,

I did a compare of the new sample version of the **hw_config.c** with the old one and changed the new one to the settings of our old one in /Pico_1140/Pico_1140_DC/.

There is the following line missing in the new one after the includes:
`void spi_dma_isr();`

and then there some additional lines after the pin-definition 
**static spi_t spis[]**
named:
```
        .set_drive_strength = true,
        .mosi_gpio_drive_strength = GPIO_DRIVE_STRENGTH_2MA,
        .sck_gpio_drive_strength = GPIO_DRIVE_STRENGTH_2MA,
```

As attachment the new hw_config.h which works with no-OS from 10.02.2023
and the "old" ones for ff14/old_ff15 for your SPI-Pinout and for RunCPM/RC2040 SPI-Pinout.

Check the difference also between 
hw_config.c_ff15new
and
hw_config.c_ff15new_guido1140 (which is also the same as the new hw_config.h)


[hw_config.zip](https://github.com/Isysxp/Pico_1140/files/10716531/hw_config.zip)

Kind regards
Guido

**Comment by Isysxp** [comment]
Dear Guido,

 Thanks for looking at this. It looks like the no-os-fatfs is a bit of a moving target at the moment.
 Not an uncommon occurrence and typical of Linux as I am sure you know.
 Thanks for adding the update code. But I think I will leave things alone in the repo at the moment as the ff14a snapshot works OK.
 However, if you have a working copy of this, I could easily add a branch along with a copy of no-OS ff15.
 NB you do not seem to have a github account. If you set on up, I can add you in as a collaborator.
 In the meanwhile, I have just received a sysgened build of RSX11M. This does run but is way over the top for this app.
 The main thing being not enough memory. However, you would not run a datacentre on Picos .... or would you???????
 One option is to move to an ESP32 which has a lot more ram. Might give it a go....

Regards, Ian.

________________________________

**Comment by spoofy-zz** [comment]
Of course, I don't mean running a data center, but RSX can be a very nice little OS. I'm still trying to generate an even smaller image, and I hope I'll be able to make it work without crashing. At least the EDT editor. As for the compiler, I put f77 and it works ok.
This is my git account.

**Comment by Isysxp** [comment]
Dear Bruno,

 Thanks for your efforts. I have done a bit more work today to find the EDT crash. It is due to a halt instruction in user mode.
 In addition, this also happens when ACNT exits via ^Z ... if it is not INS first. However, I also have an older build of RSX3.1.
 There is no EDT included but ACNT behaves as it should.
 This is a most curious error, and my first thought was problem with the KT11. But nothing obvious as in no traps/errors etc.
 I would ask if you actually build the apps from source during sysgen.
 Having said this, Simh is OK with your image and runs EDT even with 96KW memory.
NB How did you create it? As it was not done using Simh. Have you got a real machine??????

Regards, Ian.


________________________________

**Comment by spoofy-zz** [comment]
I make it in simh. 1st step was copy rl01 baseline image to rl02 with BRU and then sysgen this rl02 image in simh simulated machine. All tasks are assembled from source because EDT, DAD, BRU and some other tasks are not included in baseline system and need to be made from source.
In attachment is my sim.ini for simh with which is image maked.
[sim.ini.zip](https://github.com/Isysxp/Pico_1140/files/10717058/sim.ini.zip)

**Comment by Isysxp** [comment]
Dear Bruno,

 Thanks again for this image. I have now fixed the crashes ... this was due to an obscure fault in the RL02 handler.
 EDT now runs fine and seems OK. I have increased the memory slightly to 112k .. but 96k seems OK as well.
 Hopefully the compilers will work.....

Regards, Ian.
________________________________

**Comment by spoofy-zz** [comment]
Perfect, I am so Happy now.
Compilers are not installed yet, but as soon as they are I will put them here.
Do we need two additional console ports in image if serial + USB works in parallel? I have no way to try

**Comment by Isysxp** [comment]
Dear Bruno,

 Excellent. You can either USB or serial ... or both if you wish!
 Please note, the .uf2 version in the repo does not wait for a USB connect.
 The if you build the source code yourself, the app will wait for a USB connect.
 This is enabled/disabled by line 106 in Pico_1140.cxx.
 This is the option for people who just use the serial ports.

Regards, Ian.
________________________________

**Comment by guidol70** [comment]
> Dear Guido, Thanks for looking at this. It looks like the no-os-fatfs is a bit of a moving target at the moment. Thanks for adding the update code. But I think I will leave things alone in the repo at the moment as the ff14a snapshot works OK. However, if you have a working copy of this, I could easily add a branch along with a copy of no-OS ff15. 


Dear Ian,
Yesterday (**25.02.2023**) there were a new **Release v1.8.0** for the no-OS-**ff15** which does also work/compile with the edited hw_config.h.

As attachment a working copy (with a cleared images directory - because of the size).
The hw_config.h is configured for your (Ian) hardware-spi 
(no RunCPM/RC2040 example, but thats only changing the pin numbers)

Kind regards
Guido


[Pico_1140_newff_v108.zip](https://github.com/Isysxp/Pico_1140/files/10833717/Pico_1140_newff_v108.zip)

**Comment by Isysxp** [comment]
Hi Guido,

 Many apologies for not getting back to you about updating the SDCard library. As you may have seen, things have moved on a bit since this time last year. Overall, I doubt is there is much of an advantage adding an update as the simulation is not appreciably IO bound. I don't think that this project is worth updating unless any glaring errors arise. As mentioned in the README, I have been working on an ESP32 build which is now fairly stable at: https://github.com/Isysxp/PDP11-on-the-M5-Core. Clearly this app could be 'Bluetoothed' as well and this would be interesting.
In the meanwhile, please let me know your thoughts but I think I will close this repo in in favour of the M5 version.
To this end, many thanks again for all of your suggestions.

Best wishes, Ian.

**Comment by guidol70** [comment]
> Hi Guido,
> 
>  As mentioned in the README, I have been working on an ESP32 build which is now fairly stable at: https://github.com/Isysxp/PDP11-on-the-M5-Core. 
...please let me know your thoughts but I think I will close this repo in in favour of the M5 version. 
To this end, many thanks again for all of your suggestions.


Dear Ian,
for me its OK for closing the repo if you are using a M5-Core . but I didnt got a M5-Core :(
BUT many ESP32-Boards.

Is there a chance getting the M5-Core version running like on the pico (without display/buttons) - only via telnet/serial and a normal ESP32?

Sorry for the late reply - but I have seen your answer today...

Kind regards
Guido

**Comment by Isysxp** [comment]
Hi Guido,

 The problem with the Pico board is the amount of available memory ... 114688 16 bit words (112k) max.
 This is not quite enough to run a number of operating systems ... ideal is 124k. This leaves a 4k word IOpage.
 This can be done on some ESP32 chips that contain PSRAM ... not all of them do!
  12k words short doesn't sound like much but it really matters.
  Sorry I can't help a bit more here. Obviously it depends upon which OSs you would like to use. Could you let me know this
 as I may have a pico friendly version already built.

Regards, Ian.
________________________________

**Comment by guidol70** [comment]
> Hi Guido, 
This can be done on some ESP32 chips that contain PSRAM ... 
Obviously it depends upon which OSs you would like to use. 
Could you let me know this as I may have a pico friendly version already built. Regards, Ian.

Hi Ian,
I have some [TTGO VGA32 with 4MB PSRAM](https://lehwalder.wordpress.com/2021/04/07/runcpm-on-the-lilygo-ttgo-vga32-v1-4/) (they also support via FabGL-Library VGA,
PS2-Keyboard/Mouse and Audio - see https://github.com/fdivitto/FabGL
and the TTGO VGA32 has already a MicoSD-Slot.

![psram64h_vga32_v_1_4](https://github.com/Isysxp/Pico_1140/assets/5121124/cddf9743-2036-417d-840e-be955003c3e8)


For me - personally - I had the most fun with the pdp11 emulation when using RT11 (v5.4?) because of the BASIC-11 and other programming languages and the like CP/M&DOS like command prompt.

How about your feeling - is the ESP32 of the M5 Core2 faster than the RPi Pico?

Kind regards
Guido

**Comment by Isysxp** [comment]
Hi Guido,

 Just done a quick check. Overclocking the Pico to 200MHz works fine and the difference between the Pico and the ESP32 is marginal. For RT11 there is very little to be gained. The only advantage for using an ESP32 is that it will run Ultrix-11 up to kernel version 3 ... this is a close to BSD as possible for a none I/D split machine. The next step requires 22 bit addressing and I/D memory mapping. In this context, there is already a cut down version of Simh for the ESP32 that will emulate at least an 11/45 and runs BSD 2.11. (https://github.com/Spritetm/esppdp). This app is the limit for the ESP32. For anything more, use a Raspberry Pi! Or better still, buy a PiDP11 (https://obsolescence.wixsite.com/obsolescence/pidp-11) which is totally cool...

BW, Ian.
